name: Create GitHub Release

on:
    push:
        tags:
            - "*" # This is triggered when someone pushes a tag (ex. v1.0.0)

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      dist/*
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically generates a oken för autentication
